export const GET_ADDRESS_TYPE_REQUEST = "GET_ADDRESS_TYPE_REQUEST";
export const GET_ADDRESS_TYPE_SUCCESS = "GET_ADDRESS_TYPE_SUCCESS";
export const GET_ADDRESS_TYPE_FAILED = "GET_ADDRESS_TYPE_FAILED";

export const EDIT_ADDRESS_TYPE_REQUEST = "EDIT_ADDRESS_TYPE_REQUEST";
export const EDIT_ADDRESS_TYPE_SUCCESS = "EDIT_ADDRESS_TYPE_SUCCESS";
export const EDIT_ADDRESS_TYPE_FAILED = "EDIT_ADDRESS_TYPE_FAILED";

export const DELETE_ADDRESS_TYPE_REQUEST = "DELETE_ADDRESS_TYPE_REQUEST";
export const DELETE_ADDRESS_TYPE_SUCCESS = "DELETE_ADDRESS_TYPE_SUCCESS";
export const DELETE_ADDRESS_TYPE_FAILED = "DELETE_ADDRESS_TYPE_FAILED";