export const GET_JOB_TYPE_REQUEST = "GET_JOB_TYPE_REQUEST";
export const GET_JOB_TYPE_SUCCESS = "GET_JOB_TYPE_SUCCESS";
export const GET_JOB_TYPE_FAILED = "GET_JOB_TYPE_FAILED";

export const EDIT_JOB_TYPE_REQUEST = "EDIT_JOB_TYPE_REQUEST";
export const EDIT_JOB_TYPE_SUCCESS = "EDIT_JOB_TYPE_SUCCESS";
export const EDIT_JOB_TYPE_FAILED = "EDIT_JOB_TYPE_FAILED";

export const DELETE_JOB_TYPE_REQUEST = "DELETE_JOB_TYPE_REQUEST";
export const DELETE_JOB_TYPE_SUCCESS = "DELETE_JOB_TYPE_SUCCESS";
export const DELETE_JOB_TYPE_FAILED = "DELETE_JOB_TYPE_FAILED";