export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_SET_TOKEN = "USER_SIGNIN_SET_TOKEN";
export const USER_LOGOUT = "USER_LOGOUT";