export const CREATE_USER_EXPERIENCES_REQUEST = "CREATE_USER_EXPERIENCES_REQUEST";
export const CREATE_USER_EXPERIENCES_SUCCESS = "CREATE_USER_EXPERIENCES_SUCCESS";
export const CREATE_USER_EXPERIENCES_FAILED = "CREATE_USER_EXPERIENCES_FAILED";

export const EDIT_USER_EXPERIENCES_REQUEST = "EDIT_USER_EXPERIENCES_REQUEST";
export const EDIT_USER_EXPERIENCES_SUCCESS = "EDIT_USER_EXPERIENCES_SUCCESS";
export const EDIT_USER_EXPERIENCES_FAILED = "EDIT_USER_EXPERIENCES_FAILED";

export const DELETE_USER_EXPERIENCES_REQUEST = "DELETE_USER_EXPERIENCES_REQUEST";
export const DELETE_USER_EXPERIENCES_SUCCESS = "DELETE_USER_EXPERIENCES_SUCCESS";
export const DELETE_USER_EXPERIENCES_FAILED = "DELETE_USER_EXPERIENCES_FAILED";