export const CREATE_USER_EMAIL_REQUEST = "CREATE_USER_EMAIL_REQUEST";
export const CREATE_USER_EMAIL_SUCCESS = "CREATE_USER_EMAIL_SUCCESS";
export const CREATE_USER_EMAIL_FAILED = "CREATE_USER_EMAIL_FAILED";

export const EDIT_USER_EMAIL_REQUEST = "EDIT_USER_EMAIL_REQUEST";
export const EDIT_USER_EMAIL_SUCCESS = "EDIT_USER_EMAIL_SUCCESS";
export const EDIT_USER_EMAIL_FAILED = "EDIT_USER_EMAIL_FAILED";

export const DELETE_USER_EMAIL_REQUEST = "DELETE_USER_EMAIL_REQUEST";
export const DELETE_USER_EMAIL_SUCCESS = "DELETE_USER_EMAIL_SUCCESS";
export const DELETE_USER_EMAIL_FAILED = "DELETE_USER_EMAIL_FAILED";