export const CREATE_USER_ADDRESS_REQUEST = "CREATE_USER_ADDRESS_REQUEST";
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS";
export const CREATE_USER_ADDRESS_FAILED = "CREATE_USER_ADDRESS_FAILED";

export const EDIT_USER_ADDRESS_REQUEST = "EDIT_USER_ADDRESS_REQUEST";
export const EDIT_USER_ADDRESS_SUCCESS = "EDIT_USER_ADDRESS_SUCCESS";
export const EDIT_USER_ADDRESS_FAILED = "EDIT_USER_ADDRESS_FAILED";

export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_FAILED = "DELETE_USER_ADDRESS_FAILED";