export const CREATE_USER_PHONE_REQUEST = "CREATE_USER_PHONE_REQUEST";
export const CREATE_USER_PHONE_SUCCESS = "CREATE_USER_PHONE_SUCCESS";
export const CREATE_USER_PHONE_FAILED = "CREATE_USER_PHONE_FAILED";

export const EDIT_USER_PHONE_REQUEST = "EDIT_USER_PHONE_REQUEST";
export const EDIT_USER_PHONE_SUCCESS = "EDIT_USER_PHONE_SUCCESS";
export const EDIT_USER_PHONE_FAILED = "EDIT_USER_PHONE_FAILED";

export const DELETE_USER_PHONE_REQUEST = "DELETE_USER_PHONE_REQUEST";
export const DELETE_USER_PHONE_SUCCESS = "DELETE_USER_PHONE_SUCCESS";
export const DELETE_USER_PHONE_FAILED = "DELETE_USER_PHONE_FAILED";