export const CREATE_USER_EDUCATIONS_REQUEST = "CREATE_USER_EDUCATIONS_REQUEST";
export const CREATE_USER_EDUCATIONS_SUCCESS = "CREATE_USER_EDUCATIONS_SUCCESS";
export const CREATE_USER_EDUCATIONS_FAILED = "CREATE_USER_EDUCATIONS_FAILED";

export const EDIT_USER_EDUCATIONS_REQUEST = "EDIT_USER_EDUCATIONS_REQUEST";
export const EDIT_USER_EDUCATIONS_SUCCESS = "EDIT_USER_EDUCATIONS_SUCCESS";
export const EDIT_USER_EDUCATIONS_FAILED = "EDIT_USER_EDUCATIONS_FAILED";

export const DELETE_USER_EDUCATIONS_REQUEST = "DELETE_USER_EDUCATIONS_REQUEST";
export const DELETE_USER_EDUCATIONS_SUCCESS = "DELETE_USER_EDUCATIONS_SUCCESS";
export const DELETE_USER_EDUCATIONS_FAILED = "DELETE_USER_EDUCATIONS_FAILED";