export const GET_STATUS_REQ = "GET_STATUS_REQ";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";

export const GET_INSTRUCTOR_REQ = "GET_INSTRUCTOR_REQ";
export const GET_INSTRUCTOR_SUCCESS = "GET_INSTRUCTOR_SUCCESS";
export const GET_INSTRUCTOR_FAIL = "GET_INSTRUCTOR_FAIL";

export const GET_PROGRAM_REQ = "GET_PROGRAM_REQ";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAIL = "GET_PROGRAM_FAIL";

export const GET_CANDIDATE_REQ = "GET_CANDIDATE_REQ";
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS";
export const GET_CANDIDATE_FAIL = "GET_CANDIDATE_FAIL";

export const GET_BATCH_REQ = "GET_BATCH_REQ";
export const GET_BATCH_SUCCESS = "GET_BATCH_SUCCESS";
export const GET_BATCH_FAIL = "GET_BATCH_FAIL";

export const BULK_DELETE_BATCH_REQ = "BULK_DELETE_BATCH_REQ";
export const BULK_DELETE_BATCH_SUCCESS = "BULK_DELETE_BATCH_SUCCESS";
export const BULK_DELETE_BATCH_FAIL = "BULK_DELETE_BATCH_FAIL";

export const CREATE_BATCH_REQ = "CREATE_BATCH_REQ";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";
export const CREATE_BATCH_FAIL = "CREATE_BATCH_FAIL";