export const GET_STATUS_REQ = "GET_STATUS_REQ";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";

export const GET_INSTRUCTOR_REQ = "GET_INSTRUCTOR_REQ";
export const GET_INSTRUCTOR_SUCCESS = "GET_INSTRUCTOR_SUCCESS";
export const GET_INSTRUCTOR_FAIL = "GET_INSTRUCTOR_FAIL";

export const GET_PROGRAM_REQ = "GET_PROGRAM_REQ";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAIL = "GET_PROGRAM_FAIL";

export const GET_CANDIDATE_REQ = "GET_CANDIDATE_REQ";
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS";
export const GET_CANDIDATE_FAIL = "GET_CANDIDATE_FAIL";

export const GET_BATCH_REQ = "GET_BATCH_REQ";
export const GET_BATCH_SUCCESS = "GET_BATCH_SUCCESS";
export const GET_BATCH_FAIL = "GET_BATCH_FAIL";

export const GET_BATCH_BY_ID_REQ = "GET_BATCH_BY_ID_REQ";
export const GET_BATCH_BY_ID_SUCCESS = "GET_BATCH_BY_ID_SUCCESS";
export const GET_BATCH_BY_ID_FAIL = "GET_BATCH_FAIL";

export const BULK_DELETE_BATCH_REQ = "BULK_DELETE_BATCH_REQ";
export const BULK_DELETE_BATCH_SUCCESS = "BULK_DELETE_BATCH_SUCCESS";
export const BULK_DELETE_BATCH_FAIL = "BULK_DELETE_BATCH_FAIL";

export const CREATE_BATCH_REQ = "CREATE_BATCH_REQ";
export const CREATE_BATCH_SUCCESS = "CREATE_BATCH_SUCCESS";
export const CREATE_BATCH_FAIL = "CREATE_BATCH_FAIL";

export const EDIT_BATCH_REQ = "EDIT_BATCH_REQ";
export const EDIT_BATCH_SUCCESS = "EDIT_BATCH_SUCCESS";
export const EDIT_BATCH_FAIL = "EDIT_BATCH_FAIL";

export const CLOSE_BATCH_REQ = "CLOSE_BATCH_REQ";
export const CLOSE_BATCH_SUCCESS = "CLOSE_BATCH_SUCCESS";
export const CLOSE_BATCH_FAIL = "CLOSE_BATCH_FAIL";

export const RUNNING_BATCH_REQ = "RUNNING_BATCH_REQ";
export const RUNNING_BATCH_SUCCESS = "RUNNING_BATCH_SUCCESS";
export const RUNNING_BATCH_FAIL = "RUNNING_BATCH_FAIL";